### ISSUE TITLE
原始数据能否提供一个百度网盘

### ISSUE THREAD

**Issue by psnow** [X-zhangyang/Real-World-Masked-Face-Dataset#2]
作者你好，很感谢你的工作。
由于github下载受限，是否能放一份原始数据到百度云网盘。
谢谢！

**Comment by X-zhangyang** [comment]
已更新，可以从以下地址下载。链接: https://pan.baidu.com/s/1Vly3K-0qjlB6M2lenTZ8PA 提取码: xhze

**Comment by psnow** [comment]
谢谢！
好像缺少part1.
