### ISSUE TITLE
Bug in Rotation in wearmask.py

### ISSUE THREAD

**Issue by rohanrao619** [X-zhangyang/Real-World-Masked-Face-Dataset#28]
In line 188 of wearmask.py, PIL's rotate function expects the rotation angle to be in degrees, but as np.arctan2 returns in units of radians, there is almost no rotation applied any time. This makes the code not work properly for tilted faces. Please look into it.

**Comment by inderpreetsingh01** [comment]
@rohanrao619 I am not able to find any module named face_recognition imported on line 99 in wearmask.py, were you able to find it?

**Comment by rohanrao619** [comment]
@inderpreetsingh01 Just install it from PyPI using : `pip install face-recognition`. It works fine !

**Comment by inderpreetsingh01** [comment]
@rohanrao619 thanks!

**Comment by inderpreetsingh01** [comment]
Hi @rohanrao619  I am not able to install the .dat file, instead baidunetdisk_3.3.2_amd64.deb is getting downloaded. Did you faced any such problem?

**Comment by rohanrao619** [comment]
@inderpreetsingh01 Sorry mate, I don't have any idea on this. I only went through the face mask augmentation code.
